sistema/urls.py
from django.contrib import admin
from django.urls import path
from inventarioAPP.views import bases
from inventarioAPP.views import inventario
from inventarioAPP.views import listInventario,insertarInventario,actualizarInventario,actualizarCantidad,bajaArticulo,desactivar
from clientes.views import index
from clientes.views import getClient
from clientes.views import insertClient
from clientes.views import updateClient
from clientes.views import deleteClient
from login.views import sesion
from login.views import cerrar_sesion
from categoria import views
from evento.views import decoraciones,validarNit,listVehiculosActivos,insertEvento,listArticulos, reservarArticulo,quitarArticulo,completarOrden,enproceso,listadoEventoProceso,anularEvento,listaArticulosReservados,completados \
,listadoEventoCompletado,marcarEntregado
from vehiculos.views import vehiculos,listVehiculos,insertarVehiculo,actualizarVehiculo,activoInactivo
from dashboard.views import indexDashboard
from facturacion.views import facturarEvento,listadoEntregados,validarReservados,facturar,eventosFacturados,listadoFacturados,verFact
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',sesion,name="login"),
    path('cliente/',index, name='cliente'),
    path('cliente/listClient/',getClient,name='listClient'),
    path('cliente/insertClient/',insertClient,name='insertClient'),
    path('cliente/updateClient/',updateClient,name="updateClient"),
    path('cliente/deleteClient/',deleteClient,name="deleteClient"),
    path('bases/', bases,name="bases"),
    path('cerrar_sesion/',cerrar_sesion,name='logout'),
    path('categoria/',views.IndexCategoria,name="categoria"),
    path('categoria/listCategorias/',views.ListCategoria,name='listCategorias'),
    path('inventario/listCategorias/',views.ListCategoria,name='inventarioListCategorias'),
    path('categoria/insertCategoria/',views.insertCategoria,name='insertCategoria'),
    path('categoria/updateCategoria/',views.updateCategoria,name= 'updateCategoria'),
    path('categoria/eliminarCategoria/',views.eliminarCategoria,name='eliminarCategoria'),
    path('inventario/',inventario,name="inventario"),
    path('inventario/listInventario/',listInventario,name='listInventario'),
    path('inventario/insertarInventario/',insertarInventario,name='insertarInventario'),
    path('inventario/actualizarInventario/',actualizarInventario,name='actualizarInventario'),
    path('inventario/actualizarCantidad/',actualizarCantidad,name='actualizarCantidad'),
    path('inventario/bajaArticulo/',bajaArticulo,name='bajaArticulo'),
    path('inventario/desactivar/',desactivar,name='desactivar'),
    path('evento/',decoraciones,name="decoraciones"),
    path('vehiculos/',vehiculos,name="vehiculos"),
    path('vehiculos/listVehiculos/',listVehiculos,name='listVehiculos'),
    path('vehiculos/insertarVehiculo/',insertarVehiculo,name='insertarVehiculo'),
    path('vehiculos/actualizarVehiculo/',actualizarVehiculo,name='actualizarVehiculo'),
    path('vehiculos/activoInactivo/',activoInactivo,name='activoInactivo'),
    path('evento/validarNit/',validarNit,name='validarNit'),
    path('evento/listVehiculosActivos/',listVehiculosActivos,name='listVehiculosActivos'),
    path('evento/insertEvento/',insertEvento,name='insertEvento'),
    path('evento/listArticulos/',listArticulos,name='listArticulos'),
    path('evento/reservarArticulo/',reservarArticulo,name='reservarArticulo'),
    path('evento/quitarArticulo/',quitarArticulo,name='quitarArticulo'),
    path('evento/completarOrden/',completarOrden,name='completarOrden'),
    path('evento/enproceso/',enproceso,name='enproceso'),
    path('evento/enproceso/listadoEventoProceso/',listadoEventoProceso,name='listadoEventoProceso'),
    path('evento/enproceso/anularEvento/',anularEvento,name='anularEvento'),
    path('evento/listaArticulosReservados/',listaArticulosReservados,name='listaArticulosReservados'),
    path('evento/completados/',completados,name='completados'),
    path('evento/completados/listadoEventoCompletado/',listadoEventoCompletado,name='listadoEventoCompletado'),
    path('evento/completados/marcarEntregado/',marcarEntregado,name='marcarEntregado'),
    path('dashboard/',indexDashboard,name='indexDashboard'),
    path('facturarEvento/',facturarEvento,name="facturarEvento"),
    path('facturarEvento/listadoEntregados/',listadoEntregados,name="listadoEntregados"),
    path('facturarEvento/validarReservados/',validarReservados,name="validarReservados"),
    path('facturarEvento/facturar/',facturar,name="facturar"),
    path('eventosFacturados/',eventosFacturados,name="eventosFacturados"),
    path('eventosFacturados/listadoFacturados/',listadoFacturados,name="listadoFacturados"),
    path('eventosFacturados/verFact/',verFact,name="verFact"),
]

clientes/models.py
from django.db import models

# Create your models here.

class Clientes(models.Model):
    cod_cliente = models.AutoField(primary_key=True)
    nit = models.CharField(max_length=20)
    nombres = models.CharField(max_length=300)
    apellidos = models.CharField(max_length=300)
    direccion = models.CharField(max_length=300)
    fechaRegistro = models.DateTimeField(auto_now_add=True)
    correo = models.EmailField()
    telefono = models.CharField(max_length=12)

clientes/views.py
from django.shortcuts import render
from datetime import datetime
from django.http import JsonResponse
from .models import Clientes
from django.contrib.auth.decorators import login_required,permission_required

# Create your views here.
@login_required
def index(request):
    return render(request,'indexClientes.html')

def getClient(request):
    cliente = Clientes.objects.all()
    datos = [{'cod_cliente':item.cod_cliente,'nit':item.nit,'nombres': item.nombres,'apellidos': item.apellidos, 'fechaRegistro': item.fechaRegistro.strftime('%d-%m-%Y'), 'correo': item.correo, 'telefono':item.telefono } for item in cliente]
    return JsonResponse(datos,safe=False)

@login_required
def insertClient(request):
    if request.method == 'POST':
        try:
            _nit = request.POST.get('nit').upper()
            _nombres = request.POST.get('nombres').upper()
            _apellidos = request.POST.get('apellidos').upper()
            _correo = request.POST.get('correo').lower()
            _telefono = request.POST.get('telefono')
            _direccion = request.POST.get('direccion').upper()
           
            if not _nit or not _nombres or not _apellidos or not _correo or not _telefono:
                respuesta = {"mensaje":"Verifica los campos no pueden ser nulos","flag":False}
                return JsonResponse(respuesta,status=400,)
            
            cliente = Clientes(nit=_nit,nombres=_nombres,apellidos=_apellidos,correo=_correo,telefono=_telefono,direccion=_direccion)
            cliente.save()
            respuesta = {"mensaje":"Guardado con exito","flag":True}
            return JsonResponse(respuesta)
        except Exception as ex:
            respuesta = {"mensaje":str(ex),"flag":False}
            return JsonResponse(respuesta,status=400)
@login_required
def updateClient(request):
     if request.method == 'POST':
        try:
            _codCliente = request.POST.get('codCliente')
            _nit = request.POST.get('nit').upper()
            _nombres = request.POST.get('nombres').upper()
            _apellidos = request.POST.get('apellidos').upper()
            _correo = request.POST.get('correo').lower()
            _telefono = request.POST.get('telefono')
            _direccion = request.POST.get('direccion').upper()
           
            if not _nit or not _nombres or not _apellidos or not _correo or not _telefono or not _codCliente:
                respuesta = {"mensaje":"Verifica los campos no pueden ser nulos","flag":False}
                return JsonResponse(respuesta,status=400,)
            
            cliente = Clientes.objects.get(pk=_codCliente)
            cliente.nit = _nit
            cliente.nombres = _nombres
            cliente.apellidos = _apellidos
            cliente.correo = _correo
            cliente.telefono = _telefono
            cliente.direccion = _direccion
            cliente.save()
            respuesta = {"mensaje":"Actualizado con exito","flag":True}
            return JsonResponse(respuesta)
        except Exception as ex:
            respuesta = {"mensaje":str(ex),"flag":False}
            return JsonResponse(respuesta,status=400)
@login_required       
def deleteClient(request):
     if request.method == 'POST':
        try:
            _codCliente = request.POST.get('codCliente')
            _nit = request.POST.get('nit')
            _nombres = request.POST.get('nombres')
            _apellidos = request.POST.get('apellidos')
           
            if not _nit or not _nombres or not _apellidos or not _codCliente :
                respuesta = {"mensaje":"Verifica los campos no pueden ser nulos","flag":False}
                return JsonResponse(respuesta,status=400,)
            
            cliente = Clientes.objects.get(pk=_codCliente)
            cliente.delete()

            respuesta = {"mensaje":"Eliminado con exito","flag":True}
            return JsonResponse(respuesta)
        except Exception as ex:
            respuesta = {"mensaje":str(ex),"flag":False}
            return JsonResponse(respuesta,status=400)

clientes/templates/indexClientes.html
{%extends 'base.html'%}

{% block title%}Clientes{%endblock%}
{% block extra_scripts %}
{{ block.super }}
<script src="../static/js/clientes.js"></script>
{% endblock %}

{% block content %}


<div>
    <div class="d-flex justify-content-end pb-3">
        {% if perms.clientes.add_clientes %}
        <button class="btn btn-success" onclick="abrirModal('I');"></button>
        <span class="mx-1"><i class="fa-solid fa-plus"></i></span>Agregar</button>
        {% endif %}
            </div>
    {% if perms.clientes.view_clientes %}             
    <table id="table">
        <thead class="table-dark bg-dark">
            <tr>
                <th>Cod Cliente</th>
                <th>Nit</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Fecha Registro</th>
                <th>Correo</th>
                <th>Telefono</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
    {% endif %}
</div>
<div class="modal fade" id="modalClientes" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="headerMondal">
                <h5 class="modal-title" id="modalCliente">Formulario Clientes</h5>
                <button type="button" class="btn btn-outline-danger" onclick="cerrarModal();">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="formularioCliente">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="tipo" name="tipo">
                    </div>
                    <div class="form-group" id="groupCodCliente">
                        <label for="codCliente">Cod Cliente</label>
                        <input type="text" class="form-control" id="codCliente" placeholder="Codigo Cliente" name="codCliente">
                    </div>
                    <div class="form-group">
                        <label for="nit">Nit</label>
                        <input type="text" class="form-control" id="nit" placeholder="Nit" name="nit">
                    </div>
                    <div class="form-group">
                        <label for="nombres">Nombres</label>
                        <input type="text" class="form-control" id="nombres" placeholder="Nombres" name="nombres">
                    </div>
                    <div class="form-group">
                        <label for="apellidos">Apellidos</label>
                        <input type="text" class="form-control" id="apellidos" placeholder="Apellidos" name="apellidos">
                    </div>
                    <div class="form-group">
                        <label for="correo" id="labelCorreo">Correo</label>
                        <input type="text" class="form-control" id="correo" placeholder="Correo" name="correo">
                    </div>
                    <div class="form-group">
                        <label for="telefono" id="labelTelefono">Telefono</label>
                        <input type="text" class="form-control" id="telefono" placeholder="Telefono" name="telefono">
                    </div>
                    <div class="form-group" id="groupDireccion">
                        <label for="direccion" id="labelDireccion">Direccion</label>
                        <input type="text" class="form-control" id="direccion" placeholder="Direccion" name="direccion">
                    </div>
                    <div id="divLeyendaEliminar">
                        <h4>Esta seguro de eliminar este cliente?</h4>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"
                    onclick="cerrarModal();">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="modificarCliente();" id="btnConfirmar"><span
                        id="btnTitulo">Guardar</span></button>
            </div>
        </div>
    </div>
</div>

{% endblock %}