sistema/urls.py
from django.contrib import admin
from django.urls import path
from inventarioAPP.views import bases
from inventarioAPP.views import inventario
from inventarioAPP.views import listInventario,insertarInventario,actualizarInventario,actualizarCantidad,bajaArticulo,desactivar
from clientes.views import index
from clientes.views import getClient
from clientes.views import insertClient
from clientes.views import updateClient
from clientes.views import deleteClient
from login.views import sesion
from login.views import cerrar_sesion
from categoria import views
from evento.views import decoraciones,validarNit,listVehiculosActivos,insertEvento,listArticulos, reservarArticulo,quitarArticulo,completarOrden,enproceso,listadoEventoProceso,anularEvento,listaArticulosReservados,completados \
,listadoEventoCompletado,marcarEntregado
from vehiculos.views import vehiculos,listVehiculos,insertarVehiculo,actualizarVehiculo,activoInactivo
from dashboard.views import indexDashboard
from facturacion.views import facturarEvento,listadoEntregados,validarReservados,facturar,eventosFacturados,listadoFacturados,verFact
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',sesion,name="login"),
    path('cliente/',index, name='cliente'),
    path('cliente/listClient/',getClient,name='listClient'),
    path('cliente/insertClient/',insertClient,name='insertClient'),
    path('cliente/updateClient/',updateClient,name="updateClient"),
    path('cliente/deleteClient/',deleteClient,name="deleteClient"),
    path('bases/', bases,name="bases"),
    path('cerrar_sesion/',cerrar_sesion,name='logout'),
    path('categoria/',views.IndexCategoria,name="categoria"),
    path('categoria/listCategorias/',views.ListCategoria,name='listCategorias'),
    path('inventario/listCategorias/',views.ListCategoria,name='inventarioListCategorias'),
    path('categoria/insertCategoria/',views.insertCategoria,name='insertCategoria'),
    path('categoria/updateCategoria/',views.updateCategoria,name= 'updateCategoria'),
    path('categoria/eliminarCategoria/',views.eliminarCategoria,name='eliminarCategoria'),
    path('inventario/',inventario,name="inventario"),
    path('inventario/listInventario/',listInventario,name='listInventario'),
    path('inventario/insertarInventario/',insertarInventario,name='insertarInventario'),
    path('inventario/actualizarInventario/',actualizarInventario,name='actualizarInventario'),
    path('inventario/actualizarCantidad/',actualizarCantidad,name='actualizarCantidad'),
    path('inventario/bajaArticulo/',bajaArticulo,name='bajaArticulo'),
    path('inventario/desactivar/',desactivar,name='desactivar'),
    path('evento/',decoraciones,name="decoraciones"),
    path('vehiculos/',vehiculos,name="vehiculos"),
    path('vehiculos/listVehiculos/',listVehiculos,name='listVehiculos'),
    path('vehiculos/insertarVehiculo/',insertarVehiculo,name='insertarVehiculo'),
    path('vehiculos/actualizarVehiculo/',actualizarVehiculo,name='actualizarVehiculo'),
    path('vehiculos/activoInactivo/',activoInactivo,name='activoInactivo'),
    path('evento/validarNit/',validarNit,name='validarNit'),
    path('evento/listVehiculosActivos/',listVehiculosActivos,name='listVehiculosActivos'),
    path('evento/insertEvento/',insertEvento,name='insertEvento'),
    path('evento/listArticulos/',listArticulos,name='listArticulos'),
    path('evento/reservarArticulo/',reservarArticulo,name='reservarArticulo'),
    path('evento/quitarArticulo/',quitarArticulo,name='quitarArticulo'),
    path('evento/completarOrden/',completarOrden,name='completarOrden'),
    path('evento/enproceso/',enproceso,name='enproceso'),
    path('evento/enproceso/listadoEventoProceso/',listadoEventoProceso,name='listadoEventoProceso'),
    path('evento/enproceso/anularEvento/',anularEvento,name='anularEvento'),
    path('evento/listaArticulosReservados/',listaArticulosReservados,name='listaArticulosReservados'),
    path('evento/completados/',completados,name='completados'),
    path('evento/completados/listadoEventoCompletado/',listadoEventoCompletado,name='listadoEventoCompletado'),
    path('evento/completados/marcarEntregado/',marcarEntregado,name='marcarEntregado'),
    path('dashboard/',indexDashboard,name='indexDashboard'),
    path('facturarEvento/',facturarEvento,name="facturarEvento"),
    path('facturarEvento/listadoEntregados/',listadoEntregados,name="listadoEntregados"),
    path('facturarEvento/validarReservados/',validarReservados,name="validarReservados"),
    path('facturarEvento/facturar/',facturar,name="facturar"),
    path('eventosFacturados/',eventosFacturados,name="eventosFacturados"),
    path('eventosFacturados/listadoFacturados/',listadoFacturados,name="listadoFacturados"),
    path('eventosFacturados/verFact/',verFact,name="verFact"),
]

categoria/models.py
from django.db import models

# Create your models here.
class Categorias(models.Model):
    id_categoria = models.AutoField(primary_key=True)
    nombre_categoria = models.CharField(blank=False,max_length=250)
    descripcion_categoria = models.CharField(max_length=300)
    fechaRegistro = models.DateTimeField(auto_now_add=True)

clientes/models.py
from django.db import models

# Create your models here.

class Clientes(models.Model):
    cod_cliente = models.AutoField(primary_key=True)
    nit = models.CharField(max_length=20)
    nombres = models.CharField(max_length=300)
    apellidos = models.CharField(max_length=300)
    direccion = models.CharField(max_length=300)
    fechaRegistro = models.DateTimeField(auto_now_add=True)
    correo = models.EmailField()
    telefono = models.CharField(max_length=12)

evento/models.py
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models
from clientes.models import Clientes
from inventarioAPP.models import Inventario
from vehiculos.models import Vehiculos
# Create your models here.

class Evento(models.Model):
    id_evento = models.AutoField(primary_key=True)
    nombre_evento = models.CharField(max_length=250)
    descripcion = models.CharField(max_length=300)
    direccion = models.CharField(max_length=300,blank=True)
    fecha_entrega = models.DateField(max_length=300)
    cod_cliente = models.ForeignKey(Clientes,on_delete=models.CASCADE,blank=True)
    estado = models.CharField(max_length=30,blank=True)
    abono = models.DecimalField(max_digits=10,decimal_places=2)
    precio = models.DecimalField(max_digits=10,decimal_places=2)
    id_vehiculo = models.ForeignKey(Vehiculos,on_delete=models.CASCADE,blank=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    fecha_entregado = models.DateField(null=True)
    fecha_completada = models.DateField(null=True)
    fecha_anulada = models.DateField(null=True)

class Reserva(models.Model):
    id_reserva = models.AutoField(primary_key=True)
    id_evento = models.ForeignKey(Evento,on_delete=models.CASCADE)
    nit_cliente = models.ForeignKey(Clientes,on_delete=models.CASCADE)
    fecha_registro = models.DateField()

class elemntos_reservados(models.Model):
    id_elemento = models.AutoField(primary_key=True)
    id_evento = models.ForeignKey(Evento,on_delete=models.CASCADE)
    cod_producto = models.ForeignKey(Inventario,on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    estado = models.CharField(max_length=30)

vehiculos/models.py
from django.db import models

# Create your models here.

class Vehiculos(models.Model):
    id_vehiculo = models.AutoField(primary_key=True)
    tipo_vehiculo = models.CharField(max_length=300)
    modelo = models.CharField(max_length=300)
    marca = models.CharField(max_length=300)
    placas = models.CharField(max_length=300)
    activo = models.IntegerField()

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'alertyfy/css/alertify.css'%}">
    <link rel="stylesheet" href="{% static 'alertyfy/css/themes/default.css'%}">
    <link rel="stylesheet" href="{% static 'alertyfy/css/themes/semantic.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatable/dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatable/select.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <title>Decoraciones</title>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark border-buttom bg-nav">
        <a class="navbar-brand ps-3" href="index.html">Decoraciones Willy</a>
        <!-- Navbar-->
        <div class="w-100 d-flex justify-content-end">
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
                    class="fas fa-bars"></i></button>
            <div class="w-100 align-items-center justify-content-center d-flex">
                <h1 class="display-6 text-white"></h1>
            </div>
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/cerrar_sesion">Cerrar Sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>

    </nav>
    <div id="layoutSidenav">

        <div id="layoutSidenav_nav">

            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="textura">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Información</div>
                            <a class="nav-link" href="{% url 'indexDashboard' %}">
                                <div class="sb-nav-link-icon" style="color: #FF9800;"><i
                                        class="fas fa-tachometer-alt"></i>
                                </div>
                                Dashboard
                            </a>
                            <hr>
                            <div class="sb-sidenav-menu-heading">Operaciones</div>
                           
                            {% if perms.clientes.view_clientes %}
                            <a class="nav-link" href="{% url 'cliente'%}">
                                <div class="sb-nav-link-icon" style="color: #00AAE4;"><i
                                        class="fa-solid fa-user-tie"></i>
                                </div>
                                Clientes
                            </a>
                            {% endif %}
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                                data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon" style="color:chartreuse;"><i
                                        class="fa-solid fa-boxes-stacked"></i></div>
                                Inventario
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                                data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    {% if perms.categoria.view_categorias %}
                                    <a class="nav-link" href="{% url 'categoria' %}">Categoria</a>
                                    {% endif %}
                                    {% if perms.inventarioAPP.view_inventario %}
                                    <a class="nav-link" href="{% url 'inventario'%}">Inventario</a>
                                    {% endif %}
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                                data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon " style="color:#FFCE30;"><i
                                        class="fa-regular fa-calendar"></i></div>
                                Ordenes de Evento
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
                                data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    {% if perms.evento.add_evento %}
                                    <a class="nav-link" href="{% url 'decoraciones' %}">Generar Evento</a>
                                    {%endif%}
                                    {% if perms.evento.evento_proceso %}
                                    <a class="nav-link" href="{% url 'enproceso'%}">Orden de evento en proceso</a>
                                    {%endif%}
                                    {% if perms.evento.evento_completado %}
                                    <a class="nav-link" href="{% url 'completados'%}">Orden de evento completadas</a>
                                    {%endif%}
                                </nav>
                            </div>
                            <!--Facturacion-->
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#fact"
                                aria-expanded="false" aria-controls="fact">
                                <div class="sb-nav-link-icon " style="color:#5C6BC0;">
                                    <i class="fa-solid fa-file-invoice"></i>
                                </div>
                                Facturación
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="fact" aria-labelledby="headingTwo"
                                data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    {% if perms.evento.evento_facturar %}
                                    <a class="nav-link" href="{% url 'facturarEvento' %}">Facturar Evento</a>
                                    {% endif %}
                                    {% if perms.facturacion.view_facturacion %}
                                    <a class="nav-link" href="{% url 'eventosFacturados'%}">Eventos Facturados</a>
                                    {% endif %}
                                </nav>
                            </div>
                            {% if perms.auth.view_user %}
                            <a class="nav-link" href="/admin">
                                <div class="sb-nav-link-icon" style="color: #23BAC4;">
                                    <i class="fa-regular fa-id-card"></i>
                                </div>
                                Usuarios
                            </a>
                            {% endif %}
                            {% if perms.vehiculos.view_vehiculos %}
                            <a class="nav-link" href="{% url 'vehiculos'%}">
                                <div class="sb-nav-link-icon" style="color: #EF280F;">
                                    <i class="fa-solid fa-truck"></i>
                                </div>
                                Vehiculos
                            </a>
                            {%endif%}
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Sesión iniciada: {{user.username | upper}}</div>
                        {{ user.email | lower}}
                    </div>
                </div>
            </nav>

        </div>
        <div id="layoutSidenav_content">
            <main>
                <div>
                    <div class="container_bar">
                        <p class="title">{% block title%}Titulo Barra {%endblock%}</p>
                    </div>
                    <div class="container_Body">
    
                        {% block content %}

                        {% endblock %}
                    </div>

                </div>
            </main>

        </div>
    </div>
    <div id="loading" class="load">
        <div class="text-center text-info">
            <div class="spinner-border" style="width: 6rem; height: 6rem;" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <script src="{% static 'alertyfy/js/alertify.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/datatable/dataTables.min.js'%}"></script>
    <script src="{% static 'js/datatable/dataTables.select.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/loading.js' %}"></script>

    {% block extra_scripts %}{% endblock %}
</body>

</html>